"""Probe the actual MCP wire protocol, not direct Python tool calls."""

import argparse
import asyncio
import json
from pathlib import Path
from typing import Any

from mcp import ClientSession
from pydantic import AnyUrl

from integrations.mcp_client import connect

ROOT = Path(__file__).resolve().parents[1]


class CheckError(RuntimeError):
    """Safe diagnostic generated by this probe, without request data."""


async def tool(session: ClientSession, name: str, args: dict[str, Any]) -> dict[str, Any]:
    result = await session.call_tool(name, args)
    if result.isError:
        raise CheckError(f"MCP protocol/tool error in {name}")
    if result.structuredContent is None:
        raise CheckError(f"Missing structured result in {name}")
    return result.structuredContent


async def smoke(env: dict[str, str] | None = None, live_fx: bool = False) -> dict[str, Any]:
    async with connect(env) as session:
        tools = await session.list_tools()
        resources = await session.list_resources()
        prompts = await session.list_prompts()
        if len(tools.tools) != 9 or len(resources.resources) != 3 or len(prompts.prompts) != 1:
            raise CheckError("Unexpected discovery count")
        for item in resources.resources:
            resource_result = await session.read_resource(item.uri)
            if not resource_result.contents:
                raise CheckError("Empty resource")
        await session.get_prompt("review_expense_report", {"report_id": "EXP-2026-04417"})
        per_diem = await session.read_resource(AnyUrl("tripledger://policy/per-diem"))
        content = per_diem.contents[0]
        if not hasattr(content, "text"):
            raise CheckError("Expected JSON resource text")
        allowances = json.loads(content.text)
        cap = allowances["cities"]["Milan"]["Consultant"]["hotel_nightly"]
        calls = [
            ("get_employee", {"employee_id": "EMP-2231"}),
            ("get_trip", {"trip_id": "TRP-8890"}),
            (
                "list_card_transactions",
                {"employee_id": "EMP-2231", "from": "2026-04-07", "to": "2026-04-14"},
            ),
            ("list_settled_lines", {"employee_id": "EMP-2231", "months": 12}),
            ("read_receipt", {"file_path": "receipts/L1.json"}),
            (
                "fx_convert",
                {
                    "amount": "100",
                    "from_ccy": "USD" if live_fx else "EUR",
                    "to_ccy": "EUR",
                    "on_date": "2026-04-09",
                },
            ),
            (
                "compute_totals",
                {
                    "lines": [{"line_id": "L1", "amount": "412.00", "currency": "EUR"}],
                    "caps": [
                        {
                            "line_id": "L1",
                            "rule_id": "R-03",
                            "kind": "cap_excess",
                            "limit": cap,
                            "quantity": 3,
                        }
                    ],
                    "base_currency": "EUR",
                },
            ),
            ("match_transactions", json.loads((ROOT / "examples/match-request.json").read_text())),
            ("save_decision", json.loads((ROOT / "examples/decision.json").read_text())),
        ]
        results = {}
        for name, args in calls:
            result = await tool(session, name, args)
            if not result.get("ok"):
                raise CheckError(f"{name}: {result['error']['code']}")
            results[name] = result["data"]
        cursor = results["list_card_transactions"]["next_cursor"]
        if cursor is None:
            raise CheckError("Expected a second page")
        second = await tool(
            session,
            "list_card_transactions",
            {"employee_id": "EMP-2231", "from": "2026-04-07", "to": "2026-04-14", "cursor": cursor},
        )
        if not second.get("ok"):
            raise CheckError("Page two failed")
        invalid = await tool(
            session, "get_employee", {"employee_id": "EMP-2231", "unexpected": True}
        )
        if invalid.get("ok") or invalid["error"]["code"] != "INVALID_ARGUMENTS":
            raise CheckError("Invalid input was not safely rejected")
        pairs = results["match_transactions"]["pairs"]
        if not pairs or pairs[0]["txn_id"] != "TXN-00-022":
            raise CheckError("Uber candidate missing")
        return {
            "ok": True,
            "tool_count": 9,
            "resource_count": 3,
            "prompt_count": 1,
            "tools_called": list(results),
            "all_transaction_count": len(results["list_card_transactions"]["items"])
            + len(second["data"]["items"]),
            "uber_candidate": pairs[0],
            "invalid_input_code": invalid["error"]["code"],
            "hotel_totals_from_resource": results["compute_totals"],
            "fx": results["fx_convert"],
            "queued": results["save_decision"],
        }


def main() -> int:
    parser = argparse.ArgumentParser(description="MCP verification")
    parser.add_argument(
        "--live-fx",
        action="store_true",
        help="Use public USD/EUR API instead of identity conversion",
    )
    args = parser.parse_args()
    try:
        print(json.dumps(asyncio.run(smoke(live_fx=args.live_fx)), indent=2))
        return 0
    except CheckError as error:
        print(json.dumps({"ok": False, "error": str(error)}))
        return 1
    except Exception:
        print(
            json.dumps(
                {
                    "ok": False,
                    "error": "MCP check failed. Start mocks first; check server stderr.",
                }
            )
        )
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
